// Generated by CoffeeScript 1.4.0
var UKPKG, i, _i;

UKPKG = [];

for (i = _i = 0; _i <= 1120; i = ++_i) {
  UKPKG[i] = new Object();
}

UKPKG[0] = UKPKG[1];

UKPKG[1]['Priority Mail'] = 42.00;

UKPKG[1]['First-Class'] = 6.55;

UKPKG[2]['Priority Mail'] = 42.00;

UKPKG[2]['First-Class'] = 6.55;

UKPKG[3]['Priority Mail'] = 42.00;

UKPKG[3]['First-Class'] = 9.45;

UKPKG[4]['Priority Mail'] = 42.00;

UKPKG[4]['First-Class'] = 9.45;

UKPKG[5]['Priority Mail'] = 42.00;

UKPKG[5]['First-Class'] = 12.75;

UKPKG[6]['Priority Mail'] = 42.00;

UKPKG[6]['First-Class'] = 12.75;

UKPKG[7]['Priority Mail'] = 42.00;

UKPKG[7]['First-Class'] = 12.75;

UKPKG[8]['Priority Mail'] = 42.00;

UKPKG[8]['First-Class'] = 12.75;

UKPKG[9]['Priority Mail'] = 42.00;

UKPKG[9]['First-Class'] = 14.90;

UKPKG[10]['Priority Mail'] = 42.00;

UKPKG[10]['First-Class'] = 14.90;

UKPKG[11]['Priority Mail'] = 42.00;

UKPKG[11]['First-Class'] = 14.90;

UKPKG[12]['Priority Mail'] = 42.00;

UKPKG[12]['First-Class'] = 14.90;

UKPKG[13]['Priority Mail'] = 42.00;

UKPKG[13]['First-Class'] = 16.75;

UKPKG[14]['Priority Mail'] = 42.00;

UKPKG[14]['First-Class'] = 16.75;

UKPKG[15]['Priority Mail'] = 42.00;

UKPKG[15]['First-Class'] = 16.75;

UKPKG[16]['Priority Mail'] = 42.00;

UKPKG[16]['First-Class'] = 16.75;

UKPKG[17]['Priority Mail'] = 45.85;

UKPKG[17]['First-Class'] = 18.60;

UKPKG[18]['Priority Mail'] = 45.85;

UKPKG[18]['First-Class'] = 18.60;

UKPKG[19]['Priority Mail'] = 45.85;

UKPKG[19]['First-Class'] = 18.60;

UKPKG[20]['Priority Mail'] = 45.85;

UKPKG[20]['First-Class'] = 18.60;

UKPKG[21]['Priority Mail'] = 45.85;

UKPKG[21]['First-Class'] = 20.45;

UKPKG[22]['Priority Mail'] = 45.85;

UKPKG[22]['First-Class'] = 20.45;

UKPKG[23]['Priority Mail'] = 45.85;

UKPKG[23]['First-Class'] = 20.45;

UKPKG[24]['Priority Mail'] = 45.85;

UKPKG[24]['First-Class'] = 20.45;

UKPKG[25]['Priority Mail'] = 45.85;

UKPKG[25]['First-Class'] = 22.30;

UKPKG[26]['Priority Mail'] = 45.85;

UKPKG[26]['First-Class'] = 22.30;

UKPKG[27]['Priority Mail'] = 45.85;

UKPKG[27]['First-Class'] = 22.30;

UKPKG[28]['Priority Mail'] = 45.85;

UKPKG[28]['First-Class'] = 22.30;

UKPKG[29]['Priority Mail'] = 45.85;

UKPKG[29]['First-Class'] = 24.15;

UKPKG[30]['Priority Mail'] = 45.85;

UKPKG[30]['First-Class'] = 24.15;

UKPKG[31]['Priority Mail'] = 45.85;

UKPKG[31]['First-Class'] = 24.15;

UKPKG[32]['Priority Mail'] = 45.85;

UKPKG[32]['First-Class'] = 24.15;

UKPKG[33]['Priority Mail'] = 49.70;

UKPKG[33]['First-Class'] = 26.00;

UKPKG[34]['Priority Mail'] = 49.70;

UKPKG[34]['First-Class'] = 26.00;

UKPKG[35]['Priority Mail'] = 49.70;

UKPKG[35]['First-Class'] = 26.00;

UKPKG[36]['Priority Mail'] = 49.70;

UKPKG[36]['First-Class'] = 26.00;

UKPKG[37]['Priority Mail'] = 49.70;

UKPKG[37]['First-Class'] = 27.85;

UKPKG[38]['Priority Mail'] = 49.70;

UKPKG[38]['First-Class'] = 27.85;

UKPKG[39]['Priority Mail'] = 49.70;

UKPKG[39]['First-Class'] = 27.85;

UKPKG[40]['Priority Mail'] = 49.70;

UKPKG[40]['First-Class'] = 27.85;

UKPKG[41]['Priority Mail'] = 49.70;

UKPKG[41]['First-Class'] = 29.70;

UKPKG[42]['Priority Mail'] = 49.70;

UKPKG[42]['First-Class'] = 29.70;

UKPKG[43]['Priority Mail'] = 49.70;

UKPKG[43]['First-Class'] = 29.70;

UKPKG[44]['Priority Mail'] = 49.70;

UKPKG[44]['First-Class'] = 29.70;

UKPKG[45]['Priority Mail'] = 49.70;

UKPKG[45]['First-Class'] = 31.55;

UKPKG[46]['Priority Mail'] = 49.70;

UKPKG[46]['First-Class'] = 31.55;

UKPKG[47]['Priority Mail'] = 49.70;

UKPKG[47]['First-Class'] = 31.55;

UKPKG[48]['Priority Mail'] = 49.70;

UKPKG[48]['First-Class'] = 31.55;

UKPKG[49]['Priority Mail'] = 53.55;

UKPKG[49]['First-Class'] = 33.40;

UKPKG[50]['Priority Mail'] = 53.55;

UKPKG[50]['First-Class'] = 33.40;

UKPKG[51]['Priority Mail'] = 53.55;

UKPKG[51]['First-Class'] = 33.40;

UKPKG[52]['Priority Mail'] = 53.55;

UKPKG[52]['First-Class'] = 33.40;

UKPKG[53]['Priority Mail'] = 53.55;

UKPKG[53]['First-Class'] = 35.25;

UKPKG[54]['Priority Mail'] = 53.55;

UKPKG[54]['First-Class'] = 35.25;

UKPKG[55]['Priority Mail'] = 53.55;

UKPKG[55]['First-Class'] = 35.25;

UKPKG[56]['Priority Mail'] = 53.55;

UKPKG[56]['First-Class'] = 35.25;

UKPKG[57]['Priority Mail'] = 53.55;

UKPKG[57]['First-Class'] = 37.10;

UKPKG[58]['Priority Mail'] = 53.55;

UKPKG[58]['First-Class'] = 37.10;

UKPKG[59]['Priority Mail'] = 53.55;

UKPKG[59]['First-Class'] = 37.10;

UKPKG[60]['Priority Mail'] = 53.55;

UKPKG[60]['First-Class'] = 37.10;

UKPKG[61]['Priority Mail'] = 53.55;

UKPKG[61]['First-Class'] = 38.95;

UKPKG[62]['Priority Mail'] = 53.55;

UKPKG[62]['First-Class'] = 38.95;

UKPKG[63]['Priority Mail'] = 53.55;

UKPKG[63]['First-Class'] = 38.95;

UKPKG[64]['Priority Mail'] = 53.55;

UKPKG[64]['First-Class'] = 38.95;

UKPKG[65]['Priority Mail'] = 57.40;

UKPKG[66]['Priority Mail'] = 57.40;

UKPKG[67]['Priority Mail'] = 57.40;

UKPKG[68]['Priority Mail'] = 57.40;

UKPKG[69]['Priority Mail'] = 57.40;

UKPKG[70]['Priority Mail'] = 57.40;

UKPKG[71]['Priority Mail'] = 57.40;

UKPKG[72]['Priority Mail'] = 57.40;

UKPKG[73]['Priority Mail'] = 57.40;

UKPKG[74]['Priority Mail'] = 57.40;

UKPKG[75]['Priority Mail'] = 57.40;

UKPKG[76]['Priority Mail'] = 57.40;

UKPKG[77]['Priority Mail'] = 57.40;

UKPKG[78]['Priority Mail'] = 57.40;

UKPKG[79]['Priority Mail'] = 57.40;

UKPKG[80]['Priority Mail'] = 57.40;

UKPKG[81]['Priority Mail'] = 60.35;

UKPKG[82]['Priority Mail'] = 60.35;

UKPKG[83]['Priority Mail'] = 60.35;

UKPKG[84]['Priority Mail'] = 60.35;

UKPKG[85]['Priority Mail'] = 60.35;

UKPKG[86]['Priority Mail'] = 60.35;

UKPKG[87]['Priority Mail'] = 60.35;

UKPKG[88]['Priority Mail'] = 60.35;

UKPKG[89]['Priority Mail'] = 60.35;

UKPKG[90]['Priority Mail'] = 60.35;

UKPKG[91]['Priority Mail'] = 60.35;

UKPKG[92]['Priority Mail'] = 60.35;

UKPKG[93]['Priority Mail'] = 60.35;

UKPKG[94]['Priority Mail'] = 60.35;

UKPKG[95]['Priority Mail'] = 60.35;

UKPKG[96]['Priority Mail'] = 60.35;

UKPKG[97]['Priority Mail'] = 63.30;

UKPKG[98]['Priority Mail'] = 63.30;

UKPKG[99]['Priority Mail'] = 63.30;

UKPKG[100]['Priority Mail'] = 63.30;

UKPKG[101]['Priority Mail'] = 63.30;

UKPKG[102]['Priority Mail'] = 63.30;

UKPKG[103]['Priority Mail'] = 63.30;

UKPKG[104]['Priority Mail'] = 63.30;

UKPKG[105]['Priority Mail'] = 63.30;

UKPKG[106]['Priority Mail'] = 63.30;

UKPKG[107]['Priority Mail'] = 63.30;

UKPKG[108]['Priority Mail'] = 63.30;

UKPKG[109]['Priority Mail'] = 63.30;

UKPKG[110]['Priority Mail'] = 63.30;

UKPKG[111]['Priority Mail'] = 63.30;

UKPKG[112]['Priority Mail'] = 63.30;

UKPKG[113]['Priority Mail'] = 66.25;

UKPKG[114]['Priority Mail'] = 66.25;

UKPKG[115]['Priority Mail'] = 66.25;

UKPKG[116]['Priority Mail'] = 66.25;

UKPKG[117]['Priority Mail'] = 66.25;

UKPKG[118]['Priority Mail'] = 66.25;

UKPKG[119]['Priority Mail'] = 66.25;

UKPKG[120]['Priority Mail'] = 66.25;

UKPKG[121]['Priority Mail'] = 66.25;

UKPKG[122]['Priority Mail'] = 66.25;

UKPKG[123]['Priority Mail'] = 66.25;

UKPKG[124]['Priority Mail'] = 66.25;

UKPKG[125]['Priority Mail'] = 66.25;

UKPKG[126]['Priority Mail'] = 66.25;

UKPKG[127]['Priority Mail'] = 66.25;

UKPKG[128]['Priority Mail'] = 66.25;

UKPKG[129]['Priority Mail'] = 69.20;

UKPKG[130]['Priority Mail'] = 69.20;

UKPKG[131]['Priority Mail'] = 69.20;

UKPKG[132]['Priority Mail'] = 69.20;

UKPKG[133]['Priority Mail'] = 69.20;

UKPKG[134]['Priority Mail'] = 69.20;

UKPKG[135]['Priority Mail'] = 69.20;

UKPKG[136]['Priority Mail'] = 69.20;

UKPKG[137]['Priority Mail'] = 69.20;

UKPKG[138]['Priority Mail'] = 69.20;

UKPKG[139]['Priority Mail'] = 69.20;

UKPKG[140]['Priority Mail'] = 69.20;

UKPKG[141]['Priority Mail'] = 69.20;

UKPKG[142]['Priority Mail'] = 69.20;

UKPKG[143]['Priority Mail'] = 69.20;

UKPKG[144]['Priority Mail'] = 69.20;

UKPKG[145]['Priority Mail'] = 72.15;

UKPKG[146]['Priority Mail'] = 72.15;

UKPKG[147]['Priority Mail'] = 72.15;

UKPKG[148]['Priority Mail'] = 72.15;

UKPKG[149]['Priority Mail'] = 72.15;

UKPKG[150]['Priority Mail'] = 72.15;

UKPKG[151]['Priority Mail'] = 72.15;

UKPKG[152]['Priority Mail'] = 72.15;

UKPKG[153]['Priority Mail'] = 72.15;

UKPKG[154]['Priority Mail'] = 72.15;

UKPKG[155]['Priority Mail'] = 72.15;

UKPKG[156]['Priority Mail'] = 72.15;

UKPKG[157]['Priority Mail'] = 72.15;

UKPKG[158]['Priority Mail'] = 72.15;

UKPKG[159]['Priority Mail'] = 72.15;

UKPKG[160]['Priority Mail'] = 72.15;

UKPKG[161]['Priority Mail'] = 75.00;

UKPKG[162]['Priority Mail'] = 75.00;

UKPKG[163]['Priority Mail'] = 75.00;

UKPKG[164]['Priority Mail'] = 75.00;

UKPKG[165]['Priority Mail'] = 75.00;

UKPKG[166]['Priority Mail'] = 75.00;

UKPKG[167]['Priority Mail'] = 75.00;

UKPKG[168]['Priority Mail'] = 75.00;

UKPKG[169]['Priority Mail'] = 75.00;

UKPKG[170]['Priority Mail'] = 75.00;

UKPKG[171]['Priority Mail'] = 75.00;

UKPKG[172]['Priority Mail'] = 75.00;

UKPKG[173]['Priority Mail'] = 75.00;

UKPKG[174]['Priority Mail'] = 75.00;

UKPKG[175]['Priority Mail'] = 75.00;

UKPKG[176]['Priority Mail'] = 75.00;

UKPKG[177]['Priority Mail'] = 77.85;

UKPKG[178]['Priority Mail'] = 77.85;

UKPKG[179]['Priority Mail'] = 77.85;

UKPKG[180]['Priority Mail'] = 77.85;

UKPKG[181]['Priority Mail'] = 77.85;

UKPKG[182]['Priority Mail'] = 77.85;

UKPKG[183]['Priority Mail'] = 77.85;

UKPKG[184]['Priority Mail'] = 77.85;

UKPKG[185]['Priority Mail'] = 77.85;

UKPKG[186]['Priority Mail'] = 77.85;

UKPKG[187]['Priority Mail'] = 77.85;

UKPKG[188]['Priority Mail'] = 77.85;

UKPKG[189]['Priority Mail'] = 77.85;

UKPKG[190]['Priority Mail'] = 77.85;

UKPKG[191]['Priority Mail'] = 77.85;

UKPKG[192]['Priority Mail'] = 77.85;

UKPKG[193]['Priority Mail'] = 80.70;

UKPKG[194]['Priority Mail'] = 80.70;

UKPKG[195]['Priority Mail'] = 80.70;

UKPKG[196]['Priority Mail'] = 80.70;

UKPKG[197]['Priority Mail'] = 80.70;

UKPKG[198]['Priority Mail'] = 80.70;

UKPKG[199]['Priority Mail'] = 80.70;

UKPKG[200]['Priority Mail'] = 80.70;

UKPKG[201]['Priority Mail'] = 80.70;

UKPKG[202]['Priority Mail'] = 80.70;

UKPKG[203]['Priority Mail'] = 80.70;

UKPKG[204]['Priority Mail'] = 80.70;

UKPKG[205]['Priority Mail'] = 80.70;

UKPKG[206]['Priority Mail'] = 80.70;

UKPKG[207]['Priority Mail'] = 80.70;

UKPKG[208]['Priority Mail'] = 80.70;

UKPKG[209]['Priority Mail'] = 83.55;

UKPKG[210]['Priority Mail'] = 83.55;

UKPKG[211]['Priority Mail'] = 83.55;

UKPKG[212]['Priority Mail'] = 83.55;

UKPKG[213]['Priority Mail'] = 83.55;

UKPKG[214]['Priority Mail'] = 83.55;

UKPKG[215]['Priority Mail'] = 83.55;

UKPKG[216]['Priority Mail'] = 83.55;

UKPKG[217]['Priority Mail'] = 83.55;

UKPKG[218]['Priority Mail'] = 83.55;

UKPKG[219]['Priority Mail'] = 83.55;

UKPKG[220]['Priority Mail'] = 83.55;

UKPKG[221]['Priority Mail'] = 83.55;

UKPKG[222]['Priority Mail'] = 83.55;

UKPKG[223]['Priority Mail'] = 83.55;

UKPKG[224]['Priority Mail'] = 83.55;

UKPKG[225]['Priority Mail'] = 86.40;

UKPKG[226]['Priority Mail'] = 86.40;

UKPKG[227]['Priority Mail'] = 86.40;

UKPKG[228]['Priority Mail'] = 86.40;

UKPKG[229]['Priority Mail'] = 86.40;

UKPKG[230]['Priority Mail'] = 86.40;

UKPKG[231]['Priority Mail'] = 86.40;

UKPKG[232]['Priority Mail'] = 86.40;

UKPKG[233]['Priority Mail'] = 86.40;

UKPKG[234]['Priority Mail'] = 86.40;

UKPKG[235]['Priority Mail'] = 86.40;

UKPKG[236]['Priority Mail'] = 86.40;

UKPKG[237]['Priority Mail'] = 86.40;

UKPKG[238]['Priority Mail'] = 86.40;

UKPKG[239]['Priority Mail'] = 86.40;

UKPKG[240]['Priority Mail'] = 86.40;

UKPKG[241]['Priority Mail'] = 89.25;

UKPKG[242]['Priority Mail'] = 89.25;

UKPKG[243]['Priority Mail'] = 89.25;

UKPKG[244]['Priority Mail'] = 89.25;

UKPKG[245]['Priority Mail'] = 89.25;

UKPKG[246]['Priority Mail'] = 89.25;

UKPKG[247]['Priority Mail'] = 89.25;

UKPKG[248]['Priority Mail'] = 89.25;

UKPKG[249]['Priority Mail'] = 89.25;

UKPKG[250]['Priority Mail'] = 89.25;

UKPKG[251]['Priority Mail'] = 89.25;

UKPKG[252]['Priority Mail'] = 89.25;

UKPKG[253]['Priority Mail'] = 89.25;

UKPKG[254]['Priority Mail'] = 89.25;

UKPKG[255]['Priority Mail'] = 89.25;

UKPKG[256]['Priority Mail'] = 89.25;

UKPKG[257]['Priority Mail'] = 92.10;

UKPKG[258]['Priority Mail'] = 92.10;

UKPKG[259]['Priority Mail'] = 92.10;

UKPKG[260]['Priority Mail'] = 92.10;

UKPKG[261]['Priority Mail'] = 92.10;

UKPKG[262]['Priority Mail'] = 92.10;

UKPKG[263]['Priority Mail'] = 92.10;

UKPKG[264]['Priority Mail'] = 92.10;

UKPKG[265]['Priority Mail'] = 92.10;

UKPKG[266]['Priority Mail'] = 92.10;

UKPKG[267]['Priority Mail'] = 92.10;

UKPKG[268]['Priority Mail'] = 92.10;

UKPKG[269]['Priority Mail'] = 92.10;

UKPKG[270]['Priority Mail'] = 92.10;

UKPKG[271]['Priority Mail'] = 92.10;

UKPKG[272]['Priority Mail'] = 92.10;

UKPKG[273]['Priority Mail'] = 94.95;

UKPKG[274]['Priority Mail'] = 94.95;

UKPKG[275]['Priority Mail'] = 94.95;

UKPKG[276]['Priority Mail'] = 94.95;

UKPKG[277]['Priority Mail'] = 94.95;

UKPKG[278]['Priority Mail'] = 94.95;

UKPKG[279]['Priority Mail'] = 94.95;

UKPKG[280]['Priority Mail'] = 94.95;

UKPKG[281]['Priority Mail'] = 94.95;

UKPKG[282]['Priority Mail'] = 94.95;

UKPKG[283]['Priority Mail'] = 94.95;

UKPKG[284]['Priority Mail'] = 94.95;

UKPKG[285]['Priority Mail'] = 94.95;

UKPKG[286]['Priority Mail'] = 94.95;

UKPKG[287]['Priority Mail'] = 94.95;

UKPKG[288]['Priority Mail'] = 94.95;

UKPKG[289]['Priority Mail'] = 97.80;

UKPKG[290]['Priority Mail'] = 97.80;

UKPKG[291]['Priority Mail'] = 97.80;

UKPKG[292]['Priority Mail'] = 97.80;

UKPKG[293]['Priority Mail'] = 97.80;

UKPKG[294]['Priority Mail'] = 97.80;

UKPKG[295]['Priority Mail'] = 97.80;

UKPKG[296]['Priority Mail'] = 97.80;

UKPKG[297]['Priority Mail'] = 97.80;

UKPKG[298]['Priority Mail'] = 97.80;

UKPKG[299]['Priority Mail'] = 97.80;

UKPKG[300]['Priority Mail'] = 97.80;

UKPKG[301]['Priority Mail'] = 97.80;

UKPKG[302]['Priority Mail'] = 97.80;

UKPKG[303]['Priority Mail'] = 97.80;

UKPKG[304]['Priority Mail'] = 97.80;

UKPKG[305]['Priority Mail'] = 92.60;

UKPKG[306]['Priority Mail'] = 92.60;

UKPKG[307]['Priority Mail'] = 92.60;

UKPKG[308]['Priority Mail'] = 92.60;

UKPKG[309]['Priority Mail'] = 92.60;

UKPKG[310]['Priority Mail'] = 92.60;

UKPKG[311]['Priority Mail'] = 92.60;

UKPKG[312]['Priority Mail'] = 92.60;

UKPKG[313]['Priority Mail'] = 92.60;

UKPKG[314]['Priority Mail'] = 92.60;

UKPKG[315]['Priority Mail'] = 92.60;

UKPKG[316]['Priority Mail'] = 92.60;

UKPKG[317]['Priority Mail'] = 92.60;

UKPKG[318]['Priority Mail'] = 92.60;

UKPKG[319]['Priority Mail'] = 92.60;

UKPKG[320]['Priority Mail'] = 92.60;

UKPKG[321]['Priority Mail'] = 94.19;

UKPKG[322]['Priority Mail'] = 94.19;

UKPKG[323]['Priority Mail'] = 94.19;

UKPKG[324]['Priority Mail'] = 94.19;

UKPKG[325]['Priority Mail'] = 94.19;

UKPKG[326]['Priority Mail'] = 94.19;

UKPKG[327]['Priority Mail'] = 94.19;

UKPKG[328]['Priority Mail'] = 94.19;

UKPKG[329]['Priority Mail'] = 94.19;

UKPKG[330]['Priority Mail'] = 94.19;

UKPKG[331]['Priority Mail'] = 94.19;

UKPKG[332]['Priority Mail'] = 94.19;

UKPKG[333]['Priority Mail'] = 94.19;

UKPKG[334]['Priority Mail'] = 94.19;

UKPKG[335]['Priority Mail'] = 94.19;

UKPKG[336]['Priority Mail'] = 94.19;

UKPKG[337]['Priority Mail'] = 96.78;

UKPKG[338]['Priority Mail'] = 96.78;

UKPKG[339]['Priority Mail'] = 96.78;

UKPKG[340]['Priority Mail'] = 96.78;

UKPKG[341]['Priority Mail'] = 96.78;

UKPKG[342]['Priority Mail'] = 96.78;

UKPKG[343]['Priority Mail'] = 96.78;

UKPKG[344]['Priority Mail'] = 96.78;

UKPKG[345]['Priority Mail'] = 96.78;

UKPKG[346]['Priority Mail'] = 96.78;

UKPKG[347]['Priority Mail'] = 96.78;

UKPKG[348]['Priority Mail'] = 96.78;

UKPKG[349]['Priority Mail'] = 96.78;

UKPKG[350]['Priority Mail'] = 96.78;

UKPKG[351]['Priority Mail'] = 96.78;

UKPKG[352]['Priority Mail'] = 96.78;

UKPKG[353]['Priority Mail'] = 99.37;

UKPKG[354]['Priority Mail'] = 99.37;

UKPKG[355]['Priority Mail'] = 99.37;

UKPKG[356]['Priority Mail'] = 99.37;

UKPKG[357]['Priority Mail'] = 99.37;

UKPKG[358]['Priority Mail'] = 99.37;

UKPKG[359]['Priority Mail'] = 99.37;

UKPKG[360]['Priority Mail'] = 99.37;

UKPKG[361]['Priority Mail'] = 99.37;

UKPKG[362]['Priority Mail'] = 99.37;

UKPKG[363]['Priority Mail'] = 99.37;

UKPKG[364]['Priority Mail'] = 99.37;

UKPKG[365]['Priority Mail'] = 99.37;

UKPKG[366]['Priority Mail'] = 99.37;

UKPKG[367]['Priority Mail'] = 99.37;

UKPKG[368]['Priority Mail'] = 99.37;
